#! /usr/bin/env ruby

# TODO:
#   add flag to show tags: --tags
#   add flag to stop running timer: --stop
#       - stop timew and kill any tmr processes
#   improve notifications: interpolate tag name; icon?
#   add error handling to `run_timer`
#   refactor `validate`: extract STDERR messages to hsh
#   add help option
#   implement option to watch `timew` (approximates a running timer)
#     - would this require forking?
#     - maybe spawn process, keep its pid and kill at end?

require 'open3'

class Timer
  attr_reader :options, :valid_tags
  TIME_BLOCK_IN_SECONDS = 25 * 60
  DEFAULTS = { blocks: 1, stop_timer: false }.freeze

  def initialize(opts)
    @valid_tags = extract_tags
    @options = extract_options(opts)
  end

  def run_timer
    system("timew start #{options[:task]} > /dev/null")
    system("notify-send 'Timer initiated for #{options[:task]}'")

    sleep(options[:blocks] * TIME_BLOCK_IN_SECONDS)

    if options[:stop_timer]
      system("timew stop > /dev/null")
      system("notify-send -u critical -t 5000 'Time blocks completed; Timer stopped'")
    else
      system("notify-send -u critical -t 60000 'Time blocks completed; Timer still running!'")
    end

    exit(0)
  end

  private
  def extract_tags
    Open3.capture2("timew tags")[0]
      .sub(/\n.+\n.+\n/, "") # remove header line
      .split(/\n+/)
      .map { |full_tag| full_tag.split[0] }
  end

  def extract_options(opts)
    options = DEFAULTS.dup

    opts.each_with_index do |opt, idx|
      if opt.eql?('-t')
        options[:task] = opts[idx + 1]
      elsif opt.eql?('-b')
        options[:blocks] = opts[idx + 1].to_i
      elsif opt.eql?('-s')
        options[:stop_timer] = true
      end
    end

    validate(options)
  end

  def validate(opts)
    if !opts[:task]
      STDERR.puts("ERROR: value -t (task) must be present")
      exit(1)
    elsif !valid_tags.include?(opts[:task])
      STDERR.puts("ERROR: value of -t (task) must be existing tag")
      exit(1)
    elsif opts[:blocks].to_s.match?(/[^123]/)
      STDERR.puts("ERROR: value of -b (blocks) must be 1, 2 or 3")
      exit(1)
    end

    opts
  end
end

Timer.new(ARGV).run_timer
